---
services:
  myapp:
    build: .
    container_name: myapp
    ports:
      - 666:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
    # Optionally, you can specify a command to override the default
    # command: ["echo", "Hello from Docker Compose"]
