---
services:
  revanced-web-patcher:
    build: .
    container_name: revanced-web-patcher
    ports:
      - 666:3000
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev